---
title: "exericese-8-plot"
author: "Linna Sun"
date: "March 1, 2017"
output: md_document
---


```{r}
# install.packages("ggplot2")
```
## Base Graphics
```{r}
housing <- read.csv("Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5]) # number of columns (from left to right)
hist(housing$Home.Value) 
```

## ggplot histogram
```{r}
library(ggplot2)
ggplot(housing, aes (x = Home.Value)) +
  geom_histogram()
```
## Base colored scatter plot
```{r}
plot(Home.Value ~ Date,
     data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",
       data=subset(housing, State == "TX"))
legend(1975, 400000,
       c("MA", "TX"), title="State",
       col=c("black", "red"),
       pch=c(1, 1))
```
## ggplot colored scatter plot
```{r}
ggplot(subset(housing, State %in% c("MA", "TX")),
       aes(x=Date,
           y=Home.Value,
           color=State))+
  geom_point()
```

## Points(scatterplot)
```{r}
help.search("geom_", package = "ggplot2")
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = Land.Value)) +
  geom_point()
```

## ggplot scatterplot
```{r}
ggplot(hp2001Q1,
       aes(y = Structure.Cost, x = log(Land.Value))) +
  geom_point()
```
## Line(prediction line)
```{r}
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))

p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))

p1 + geom_point(aes(color = Home.Value)) +
  geom_line(aes(y = pred.SC))
```
## Smoother
```{r}
p1 +
  geom_point(aes(color = Home.Value)) +
  geom_smooth()
```

## Text(label points)
```{r}
p1 + 
  geom_text(aes(label = State), size = 3)
```
##ggpel text(label point)
```{r}
# install.packages("ggrepel") 
library("ggrepel")
p1 + 
  geom_point() + 
  geom_text_repel(aes(label=State), size = 3)
```
## Aesthetic Mapping VS Assignment
```{r}

p1 +
  geom_point(aes(size = 2),# incorrect! 2 is not a variable
             color="red") # this is fine -- all points red
```
## Mapping Variables To Other Aesthetics
```{r}
p1 +
  geom_point(aes(color=Home.Value, shape = region))
```
## Exercise 1
```{r}
dat <- read.csv("Rgraphics/dataSets/EconomistData.csv")
head(dat)

ggplot(dat, aes(x = CPI, y = HDI, size = 2, colour = "blue")) + geom_point()

```




